In [14]:
import numpy as np

In [15]:
rets = np.load('chessboard_points/intrinsic_rets.npy')
objpoints = np.load('chessboard_points/intrinsic_object_points.npy')
imgpoints = np.load('chessboard_points/intrinsic_image_points.npy')
shape = np.load('chessboard_points/intrinsic_shape.npy')

In [17]:
print(rets)

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 ...
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [18]:
print(objpoints)

[[[[0.         0.         0.        ]
   [0.009      0.         0.        ]
   [0.018      0.         0.        ]
   ...
   [0.28799999 0.108      0.        ]
   [0.29699999 0.108      0.        ]
   [0.30599999 0.108      0.        ]]

  [[0.         0.         0.        ]
   [0.009      0.         0.        ]
   [0.018      0.         0.        ]
   ...
   [0.28799999 0.108      0.        ]
   [0.29699999 0.108      0.        ]
   [0.30599999 0.108      0.        ]]

  [[0.         0.         0.        ]
   [0.009      0.         0.        ]
   [0.018      0.         0.        ]
   ...
   [0.28799999 0.108      0.        ]
   [0.29699999 0.108      0.        ]
   [0.30599999 0.108      0.        ]]

  [[0.         0.         0.        ]
   [0.009      0.         0.        ]
   [0.018      0.         0.        ]
   ...
   [0.28799999 0.108      0.        ]
   [0.29699999 0.108      0.        ]
   [0.30599999 0.108      0.        ]]

  [[0.         0.         0.        ]
   [0.009     

In [12]:
print(imgpoints)

[[[[148.52818298 103.52513885]
   [161.63774109 102.9821701 ]
   [174.93051147 102.56516266]
   ...
   [532.00805664 218.54684448]
   [540.49029541 217.45559692]
   [547.         216.        ]]

  [[218.61006165  83.63822174]
   [228.43385315  90.08138275]
   [238.36671448  96.75191498]
   ...
   [445.95904541 401.76318359]
   [455.05706787 407.71115112]
   [463.65325928 413.56552124]]

  [[ 35.32398224 261.00509644]
   [ 47.64089966 261.59710693]
   [ 59.95494843 262.824646  ]
   ...
   [486.87319946 474.70425415]
   [503.28311157 477.53369141]
   [520.25415039 480.6496582 ]]

  [[139.93382263 407.60400391]
   [147.30941772 400.38122559]
   [154.78559875 392.82540894]
   ...
   [502.5916748  251.04974365]
   [511.90731812 242.59590149]
   [521.11328125 234.20523071]]

  [[190.05580139 481.98065186]
   [195.3059082  469.2789917 ]
   [200.49394226 456.82296753]
   ...
   [423.42977905 206.8087616 ]
   [426.34109497 198.21379089]
   [429.43432617 189.70698547]]]


 [[[148.52818298 103.52

In [6]:
print(shape)

[640 640]
