In [9]:
import numpy as np

In [12]:
points = np.load('points.npy')
print(points)
rets = np.load('rets.npy')
print(rets)

[[[[ 0.          0.          0.          0.        ]
   [ 0.          0.          0.          0.        ]
   [ 0.          0.          0.          0.        ]
   [ 0.          0.          0.          0.        ]]

  [[ 0.          0.          0.          0.        ]
   [ 0.          0.          0.          0.        ]
   [ 0.          0.          0.          0.        ]
   [ 0.          0.          0.          0.        ]]

  [[ 0.05021648 -0.68093008 -0.73062476  0.01123853]
   [-0.98298975 -0.16309718  0.0844421  -0.17643201]
   [-0.17666201  0.71395626 -0.67753745  0.11584531]
   [ 0.          0.          0.          1.        ]]]


 [[[ 0.          0.          0.          0.        ]
   [ 0.          0.          0.          0.        ]
   [ 0.          0.          0.          0.        ]
   [ 0.          0.          0.          0.        ]]

  [[ 0.          0.          0.          0.        ]
   [ 0.          0.          0.          0.        ]
   [ 0.          0.          0.     