In [3]:
import numpy as np
import pickle as pkl

In [2]:
points = np.load('points.npy')
print(points)
rets = np.load('rets.npy')
print(rets)

[[[ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.01123853 -0.17643201  0.11584531]]

 [[ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.01128004 -0.17631019  0.11539345]]

 [[ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.01128004 -0.17631019  0.11539345]]

 ...

 [[ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]]

 [[ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]]

 [[ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]]]
[[False False  True]
 [False False  True]
 [False False  True]
 ...
 [False False False]
 [False False False]
 [False False False]]


In [4]:
points = pkl.load('points.pkl')

TypeError: file must have 'read' and 'readline' attributes